# Nginx web server configuration
server {

  # Nginx listens on port 80
  listen 80;

  # Frontend React application
  location / {

    # Location of built React files
    root /usr/share/nginx/html;

    # Main file to open
    index index.html;

    # React routing support
    # If file not found, return index.html
    try_files $uri /index.html;
  }

  # Backend API requests
  location /api/ {

    # Forward API requests to backend service
    proxy_pass http://backend-service:5000/api/;
  }
}