# MongoDB Secret
#
# This file stores sensitive MongoDB credentials securely
# inside Kubernetes.
#
# - MongoDB username
# - MongoDB password
#
# The backend and MongoDB containers read these values
# as environment variables.

# Standard Kubernetes API version
apiVersion: v1

# Resource type
# Secret stores sensitive information
kind: Secret

metadata:
  # Name of the Secret
  name: mongo-secret

# Opaque means generic user-defined secret data
type: Opaque

# Secret key-value pairs
stringData:

  # MongoDB username
  MONGO_USERNAME: admin

  # MongoDB password
  MONGO_PASSWORD: password123